import { useEffect, useState } from 'react';
import { View, Text, TextInput, TouchableOpacity, FlatList, Alert, StyleSheet } from 'react-native';
import { useLocalSearchParams, router } from 'expo-router';
import { journeyService } from '../../../src/services/journey.service';
import { Colors } from '../../../src/theme';

export default function MembersScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const [query, setQuery] = useState(''), [users, setUsers] = useState<any[]>([]), [loading, setLoading] = useState(false);
  useEffect(() => { const timer = setTimeout(async () => { if (query.trim().length < 2) return setUsers([]); setLoading(true); try { const response: any = await journeyService.searchUsers(query.trim()); setUsers(response.users || []); } catch { setUsers([]); } finally { setLoading(false); } }, 300); return () => clearTimeout(timer); }, [query]);
  const invite = async (user: any) => { try { await journeyService.inviteMember(id, user.email); Alert.alert('Invitation sent', `${user.fullName} can accept it from Notifications.`); setUsers((current) => current.filter((item) => item._id !== user._id)); } catch (error: any) { Alert.alert('Could not send invitation', error.message); } };
  return <View style={s.container}><View style={s.header}><TouchableOpacity onPress={() => router.back()}><Text>Back</Text></TouchableOpacity><Text style={s.title}>Invite collaborators</Text><View /></View><TextInput style={s.input} value={query} onChangeText={setQuery} placeholder="Search name, username, or email" autoCapitalize="none" /><FlatList data={users} keyExtractor={(item) => item._id} ListEmptyComponent={query.length >= 2 ? <Text style={s.empty}>{loading ? 'Searching…' : 'No registered users found.'}</Text> : <Text style={s.empty}>Search for someone to invite.</Text>} renderItem={({ item }) => <View style={s.user}><View><Text style={s.name}>{item.fullName}</Text><Text>{item.username ? `@${item.username}` : item.email}</Text></View><TouchableOpacity style={s.invite} onPress={() => invite(item)}><Text style={s.inviteText}>Invite</Text></TouchableOpacity></View>} /></View>;
}
const s = StyleSheet.create({ container: { flex: 1, backgroundColor: Colors.background.primary }, header: { padding: 20, flexDirection: 'row', justifyContent: 'space-between', backgroundColor: Colors.background.secondary }, title: { fontSize: 18, fontWeight: '700' }, input: { margin: 16, borderWidth: 1, borderColor: Colors.border.light, borderRadius: 12, padding: 14, backgroundColor: Colors.background.secondary }, user: { marginHorizontal: 16, paddingVertical: 14, borderBottomWidth: 1, borderColor: Colors.border.light, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, name: { fontWeight: '700' }, invite: { backgroundColor: Colors.primary.main, borderRadius: 8, padding: 10 }, inviteText: { color: '#fff', fontWeight: '700' }, empty: { textAlign: 'center', marginTop: 35, color: Colors.text.tertiary } });
