import { useState } from 'react';
import { View, Text, TextInput, TouchableOpacity, ScrollView, Image, Alert, ActivityIndicator, StyleSheet, Modal } from 'react-native';
import { router } from 'expo-router';
import * as ImagePicker from 'expo-image-picker';
import * as Location from 'expo-location';
import MapView, { Marker, MapPressEvent } from 'react-native-maps';
import DateTimePicker from '@react-native-community/datetimepicker';
import { useJourneyStore } from '../../src/store';
import { Colors } from '../../src/theme';

export default function CreateJourneyScreen() {
  const [title, setTitle] = useState(''), [description, setDescription] = useState(''), [location, setLocation] = useState(''), [coverImage, setCoverImage] = useState<string | null>(null);
  const [startDate, setStartDate] = useState(new Date()), [endDate, setEndDate] = useState(new Date()), [dateField, setDateField] = useState<'start' | 'end' | null>(null);
  const [mapVisible, setMapVisible] = useState(false), [pin, setPin] = useState<{ latitude: number; longitude: number } | null>(null), [region, setRegion] = useState({ latitude: 20.5937, longitude: 78.9629, latitudeDelta: 12, longitudeDelta: 12 });
  const { createJourney, fetchJourneys, isLoading } = useJourneyStore();
  const reset = () => { setTitle(''); setDescription(''); setLocation(''); setCoverImage(null); setStartDate(new Date()); setEndDate(new Date()); setPin(null); };
  const pickImage = async () => { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return Alert.alert('Permission required', 'Allow photo access to choose a cover image.'); const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], allowsEditing: true, aspect: [16, 9], quality: .8 }); if (!result.canceled) setCoverImage(result.assets[0].uri); };
  const choosePlace = async (event: MapPressEvent) => { const coordinate = event.nativeEvent.coordinate; setPin(coordinate); try { const place = (await Location.reverseGeocodeAsync(coordinate))[0]; if (place) setLocation([place.city || place.district, place.region, place.country].filter(Boolean).join(', ')); } catch { Alert.alert('Location selected', 'Coordinates will still be saved.'); } };
  const submit = async () => { if (!title.trim() || !description.trim()) return Alert.alert('Missing details', 'Add a title and description.'); if (endDate < startDate) return Alert.alert('Invalid dates', 'End date cannot be before start date.'); const data = new FormData(); [['title', title.trim()], ['description', description.trim()], ['location', location.trim()], ['startDate', startDate.toISOString()], ['endDate', endDate.toISOString()]].forEach(([key, value]) => data.append(key, value)); if (pin) { data.append('latitude', String(pin.latitude)); data.append('longitude', String(pin.longitude)); } if (coverImage) { data.append('coverImage', { uri: coverImage, name: 'cover.jpg', type: 'image/jpeg' } as never); } try { await createJourney(data); await fetchJourneys(); reset(); Alert.alert('Journey created', 'Your journey is ready.', [{ text: 'View journeys', onPress: () => router.replace('/journeys') }]); } catch (error: any) { Alert.alert('Could not create journey', error.message || 'Try again.'); } };
  return <ScrollView style={s.container}><View style={s.header}><Text style={s.title}>Create Journey</Text></View><View style={s.form}><TouchableOpacity style={s.imagePicker} onPress={pickImage}>{coverImage ? <Image source={{ uri: coverImage }} style={s.cover} /> : <Text>Add Cover Image (optional)</Text>}</TouchableOpacity><TextInput style={s.input} value={title} onChangeText={setTitle} placeholder="Journey title *" /><TextInput style={[s.input, s.area]} value={description} onChangeText={setDescription} multiline placeholder="Description *" /><View style={s.row}><TouchableOpacity style={s.date} onPress={() => setDateField('start')}><Text>Start: {startDate.toLocaleDateString()}</Text></TouchableOpacity><TouchableOpacity style={s.date} onPress={() => setDateField('end')}><Text>End: {endDate.toLocaleDateString()}</Text></TouchableOpacity></View>{dateField && <DateTimePicker value={dateField === 'start' ? startDate : endDate} mode="date" onChange={(_, value) => { setDateField(null); if (value) { if (dateField === 'start') setStartDate(value); else setEndDate(value); } }} />}<TouchableOpacity style={s.input} onPress={() => setMapVisible(true)}><Text>{location || 'Choose location on map'}</Text></TouchableOpacity><TouchableOpacity style={s.button} disabled={isLoading} onPress={submit}>{isLoading ? <ActivityIndicator color="#fff" /> : <Text style={s.buttonText}>Launch Journey</Text>}</TouchableOpacity></View><Modal visible={mapVisible} animationType="slide"><View style={s.mapBox}><View style={s.mapHeader}><TouchableOpacity onPress={() => setMapVisible(false)}><Text>Close</Text></TouchableOpacity><Text style={s.title}>Pick a location</Text><TouchableOpacity onPress={async () => { const permission = await Location.requestForegroundPermissionsAsync(); if (permission.granted) { const current = await Location.getCurrentPositionAsync({}); setRegion({ ...current.coords, latitudeDelta: .08, longitudeDelta: .08 }); } }}><Text>My location</Text></TouchableOpacity></View><MapView style={s.map} region={region} onRegionChangeComplete={setRegion} onPress={choosePlace}>{pin && <Marker coordinate={pin} />}</MapView><TouchableOpacity style={s.button} onPress={() => setMapVisible(false)}><Text style={s.buttonText}>Confirm {location || 'location'}</Text></TouchableOpacity></View></Modal></ScrollView>;
}
const s = StyleSheet.create({ container: { flex: 1, backgroundColor: Colors.background.primary }, header: { padding: 20, backgroundColor: Colors.background.secondary }, title: { fontSize: 20, fontWeight: '700', color: Colors.text.primary }, form: { padding: 20, gap: 12 }, imagePicker: { height: 190, borderWidth: 1, borderColor: Colors.primary.main, borderRadius: 16, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }, cover: { width: '100%', height: '100%' }, input: { borderWidth: 1, borderColor: Colors.border.light, borderRadius: 12, padding: 14, backgroundColor: Colors.background.secondary }, area: { height: 100, textAlignVertical: 'top' }, row: { flexDirection: 'row', gap: 8 }, date: { flex: 1, borderWidth: 1, borderColor: Colors.border.light, borderRadius: 12, padding: 14 }, button: { backgroundColor: Colors.primary.main, padding: 16, borderRadius: 12, alignItems: 'center' }, buttonText: { color: '#fff', fontSize: 16, fontWeight: '700' }, mapBox: { flex: 1 }, mapHeader: { padding: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, map: { flex: 1 } });
